# Generated by Django 3.1.5 on 2021-01-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_auto_20210129_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conse',
            options={'managed': True, 'verbose_name': 'Conse', 'verbose_name_plural': 'Conses'},
        ),
        migrations.AlterModelTable(
            name='conse',
            table='conses',
        ),
    ]
